version: "3.9"
services:
  web:
    image: node:17.7.1-alpine3.14
    command: [ "npm", "run", "dev" ]
    working_dir: /app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "3035:3035"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.10
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: pfadiolten

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "3001:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  mongo:
  node_modules:
