import useUser from '@/hooks/useUser'
import type { NextPage } from 'next'
import { signIn, signOut } from 'next-auth/react'
import Head from 'next/head'

const Home: NextPage = () => {
  const user = useUser()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {user === null ? (
          <button type="button" onClick={() => signIn('midata')}>
            Login
          </button>
        ) : (
          <button type="button" onClick={() => signOut()}>
            Logout
          </button>
        )}
        <br />
      </main>
    </div>
  )
}

export default Home
