name: "Build and Deploy"
on: [push]
permissions:
  contents: read
  packages: read
jobs:
  build:
    name: "Lint, Test, Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
        env:
          GITHUB_NPM_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run lint
      - run: npm run build
